<?php
add_filter( 'paginate_links_output', 'my_paginate_links_output', 10, 2 );
function my_paginate_links_output( $output, $args )
{
    if( $args['current'] == 1 )
    {
        $prev = '<span class="prev page-numbers inactive">'.$args['prev_text'].'</span>';
        $output = $prev . "\n" . $output;
    }

    if( $args['total'] == $args['current'] )
    {
        $next = '<span class="next page-numbers inactive">'.$args['next_text'].'</span>';
        $output .= "\n" . $next;
    }
    return $output;
}
/**
 * This function removes the "screen-reader-text" span element from the navigation markup generated by the "the_posts_pagination" function in WordPress.
 *
 * @param string $template The navigation markup template.
 * @return string The modified navigation markup template.
 */
function remove_screen_reader_text( $template ) {
    $template = preg_replace( '/<h2 class="screen-reader-text">(.*?)<\/h2>/', '', $template );
    return $template;
}
add_filter( 'navigation_markup_template', 'remove_screen_reader_text' );
